language: node_js
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- "./node_modules/.bin/bower install --silent"
addons:
  sauce_connect: true
script:
- npm run lint
- ./node_modules/.bin/polymer test --plugin sauce --job-name "authorization-data-saver:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: MxbNeLPs/4QIwq/JLn+RPlNGfHfUlraaCFhTl9KLt6cnfSczVo/AzwH6+N6gN/bi35YQOLRj50yZYYUU3lY0Nn8touaDj7WrmkrBKNcJ0N6ZYVAZQbp9mVggIXG4Ipi1cUuNpFosjmRRq3Nuc8TsBUoeFo2SOmehCxlFImWj+MJgAM3VUVZMPscl+G35/4gsVIpt2+y+7zPmXNLz17PDQQXCqoai6GlcVLTWAwgXvzal5MCDmOKHictX9tq4HjCfijTdXO7sJ2T5UsAKbX+wIrqMXzmjT3Scdo4LoA0Ijhff5IvflH21wgYWvfUAD/unA4Ri7E9f3Paw7lqJ2NDA++tWbUPPZURC/LzjsXO8fYZ1VZ2x+BtZ83LTBvbDPHNiK/dpLvd37ryZ2jfo40I8tKseYRhkKp9E4fXNUBclRLt2CMKkTnIpYat0NjS6Ck2+z83lHRzPK3zVustPCCdjI5KNWP05CdcCLMi9JgaIzl3egwkaP7ycbIt0v+ZSMMuVQNXKjwxFoFkfm25j61DKraWeVCphZDamUd/Qr9jm2RVTXhArY8NJ1hsiBWxqJP2h3/+caIVoyqjhDuPJwd7Gdk9yURF2JmvzQ2Pk75WZPojFrw1Fy8S6NqJng/Mt+sUH7+bg8XMMXTGcdMyl/hofo4pItvQIDHD2h0pVYN8o6t8=
  - secure: lPmAJJLMUVppJBrebeHG5wKesYmQ5BIGR4s961yxqQry8olqvSJk+QN14Am4/jeUFaB3VW8Fb2TN8HNZmACqYMuH/qWstBECxI95E1E9oy/UKqa1UTLm/gzEtliJ2J+Ffk0EMVwNCF7FKLqNlFhmZJ446JgzKFv52C/v1isVoKiUJNbt37ZqEf4+oyYrrrirfexgMj0xrxq9Q5OwspGOEpxnq9PiharVwOWrltcdCtkEGSDCkSzrDhQIl19+LG3c7mmMMFC5NVpNB24Ak3Acdw7cAil4hnPHotsns6zvWyP6vGi9zMbOXbTkwvNfzkPnd8sdCDypdigQ6hSlbO+P5+6YSil/8mJkcVyBDjFuXbCbfrdX0SAZfzzqOOVFf0FvZbIOf8rAmeD2NG4DrwwLgSZr12uqEcZUUbt64zL3Uu4vaDEXItczH7S4pLalwtqDyrnpven0LvArzycY2PF9Ccj14S1/NLXZUi+LHB0w0I6LOcoY5mbFYfBhDVRCxLu2G9avfhe4MgEn9Og0tKsQgchjbj4X155IXYDEHwjFhM1CSbM4tkUYaoX6NnR8+BhE4mYoLqPvU8JegxuviRWqDtLurvyqIyG0pqsmwjjCnEcqMO1zqmXU4ceqIsWhPoASyVOCHccEIVy7YXNxOihBpyrL2Oyn2GMg9BqSUFh1r88=
  - secure: Zr67ruYVLnEbhRn0tiyKN6FZv5iQTBJgBC8ercYXhITNsUX85yabZMMV38bfDJMAz398IKVIAcWMGvt8aCfpqN9sMIM4G3aPEf7XQ9UXuHhqyw76Z5JJbnNstVSnJERrpOHE1bFTg/KJ+u74dFI5sS+o3bZ+C84OMw6joq91I1X3dQd+xrJJMsPFN2cCkRxSwjAtjUGUl6QRezKYxb9GTxsMv9rJ8S+75lW4SRVVi1+MxFUP7fH5fnuHCIFxKNabELE6EPQ2ZHwNFOQG3ZJqYzjh6Zqgfyc84Z0FRih1Z6JLuEcR/YO70VT4Bf1YOmnrnOcTxTM331os/KLndA1ThJtZZSpyLOYPpvMHwzIjLZWsfI3rlw2RlOHum/LwPYA8IXlBb1F177NXpWgPaU+9km2+OQkI31l5FkTyJJHg57JVghORWtzUqBkPWJ+0vv9WGxvlv8nQYWjieF4YNl7OfB0dIz1E3JdSOOoxDjgVYOLTGCIbzbz6Hc+kOWLJGU1Tf21G+VVfnF8n1wDhtk6BmEKgn7zevfr4EpDG+NEQotHphpZLVTtRR2uiNJgG/2WJ06yyh7B41+/skZU7cAOQhRW1MjNBHdixJIf8r8sR2CFFe7PIfyyADjQ5gA5osmKyoWehK50O4a9eB8NfL8bgKyeRBCXEVqkgxexUoS8ishU=
  - secure: DKzm8uizwauOmTAp4CroA6dlyrPyX95MSlXsLzH3eJRNYkPlawgHwk0TpVGmTZ5+/rPSFPD9OQBGDtFMkpWRlRfZBpcFPH5WQFtk79Zmf21fs3B3N7Nve+oLLvT9sRfUfwkSevhflPtOb/3JMCC88eWwqUjj1FdU3CsR6uySTFJkheY1JQLAC3z8DTYUnlRy+FqsZWUsHL6bjZL5AKG5kru9bOPJy1evAKBgXl14wMTSSbJx/GPqlc9Oca3PWYBAWWPQejc8804Iqpq58mG0wDh6m7aFb3LrEh/vFu/TfullhtX/AgFNV8HWv+diZyu8uVv7WSCntn8dM6pKbuFx3st4Ema51EzJrXEEopKdxyjrJYBLM1mppJYmRk9U+HML0iFzRiJ1uRTEilxMmPqU5ty2Iw8G+QFlS5eSQuMZySjqQfS0KzKfKweUHk22PyvyrV8E3d8XmAaFJ+T9nzkJKIboS2nAiVQhXdbPvXGkOgPUmppy4JZ4w4IgXRhPT5AIcNc8j90K1u9MQNPXEb/N2fQmf9esZ/a+7U9Ua5QaT1DP/xXr1jp3sLyvWjFXeAv5Slz6PGDiBuv2W81Oh8GE5Sfwbx48PqdhkyUFH2CcdbKSjP8TPrOi5Fi8IO3ubasW+kiJjVUBK237PhHauvPqnGNerBr5BmjTNi4sbPEG3O4=
